feat:update test yml

diff --git a/.github/workflows/ci-cd-dev.yml b/.github/workflows/ci-cd-dev.yml
--- a/.github/workflows/ci-cd-dev.yml
+++ b/.github/workflows/ci-cd-dev.yml
@@ -15,6 +15,8 @@ env:
   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
   TTB_KEY: ${{ secrets.TTB_KEY }}
   REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
+  TOSS_PAYMENT_CLIENT_KEY: ${{ secrets.TOSS_PAYMENT_CLIENT_KEY }}
+  TOSS_PAYMENT_SECRET_KEY: ${{ secrets.TOSS_PAYMENT_SECRET_KEY }}
 
 jobs:
   build:
@@ -100,6 +102,7 @@ jobs:
   test:
     needs: build
     runs-on: ubuntu-latest
+
     services:
       redis:
         image: redis
@@ -147,12 +150,23 @@ jobs:
         run: sleep 30
 
       - name: Check health endpoint
-        run: curl --fail http://localhost:10270/shop/actuator/health
+        run: |
+          for i in {1..10}; do
+            echo ":hourglass_flowing_sand: Waiting for server to start... attempt $i"
+            if curl --fail http://localhost:10270/shop/actuator/health; then
+              echo ":white_check_mark: Server is up"
+              exit 0
+            fi
+            sleep 3
+          done
+          echo ":x: Server failed to start in time"
+          exit 1
 
       - name: Stop application
         run: kill $(cat app.pid)
 
       - name: Run unit tests
+
         run: |
           mvn test \
           -Dspring.profiles.active=test \
@@ -164,6 +178,7 @@ jobs:
       - name: Print app log if health check fails
         if: failure()
         run: cat app.log
+
 
   deploy:
     name: Deploy to Linux Server
